export const base = {
    'subway': {
        '0': "不限",
        '1': "1号线",
        '2': "2号线",
        '3': "3号线",
        '4': "4号线",
        '5': "5号线",
        '6': "6号线",
        '7': "7号线",
        '8': "8号线",
        '9': "9号线",
        '10': "10号线",
        '11': "11号线",
    },
    'region': {
        '0': "不限",
        '1': "罗湖区",
        '2': "福田区",
        '3': "南山区",
        '4': "龙岗区",
        '5': "盐田区",
        '6': "宝安区",
        '7': "光明新区",
        '8': "坪山新区",
        '9': "龙华新区",
        '10': "大鹏新区",
    },
    'apartment': {
        '0': "不限",
        '1': "单间",
        '2': "合租",
        '3': "一室一厅",
        '4': "两室一厅",
        '5': "其它",
    },
    'house_type': {'0': '不限', '1': '整租', '2': '合租'},
    'facilities': {
        'wifi': {name:'无线网',icon:'icon-wifi'},
        'weibolu': {name:'微波炉',icon:'icon-weibolu-'},
        'xiyiji': {name:'洗衣机',icon:'icon-xiyiji'},
        'bingxiang': {name:'冰箱',icon:'icon-bingxiang'},
        'duwei': {name:'独卫',icon:'icon-matong'},
        'dianti': {name:'电梯',icon:'icon-dianti'},
        'kongtiao': {name:'空调',icon:'icon-kongtiao-'},
        'nuanqi': {name:'暖气',icon:'icon-nuanqi-'},
        'yigui': {name:'衣柜',icon:'icon-yigui'},
        'yangtai': {name:'阳台',icon:'icon-yangtai'},
        'reshuiqi': {name:'热水器',icon:'icon-reshuiqi'},
        'zhufan': {name:'煮饭',icon:'icon-Concise'},
    }
}
